---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mumixhqm/poll.abasas.tech
    # - export DEPLOYPATH=/home/masjeebl/dev.masjidmissioncenterusa.org
    - /bin/cp -r * $DEPLOYPATH #copy all from root
    # - /bin/cp -r ./public/* $DEPLOYPATH/
    # - /bin/cp ln -nfs $DEPLOYPATH/public $DEPLOYPATH
